### ISSUE TITLE
Tour of ARLAS breaks the layout when the step is on the timeline

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-wui#765] opened 2024-03-22 16:36 UTC
### Description of the bug

When starting the tour, at the timeline step, the layout gets weird.
<img width="983" alt="image" src="https://github.com/gisaia/ARLAS-wui/assets/35499583/68c276d9-d0bd-4888-b73f-4c1ec5ed81f7">

### Steps to reproduce

go to https://demo.cloud.arlas.io/arlas/wui/?filter=%7B%7D&config_id=D57JL4ziqn8dhlDwrJ40&extend=-12.92295539288753,28.581403804655764,21.182576092975296,43.27436725282769&vs=Latest%20products;All%20products
and play the Tour

### If the issue was noticed in the demo workspace, please specify the collection and the field. Otherwise, please link the 2 ARLAS config files.

https://demo.cloud.arlas.io/arlas/wui/?filter=%7B%7D&config_id=D57JL4ziqn8dhlDwrJ40&extend=-12.92295539288753,28.581403804655764,21.182576092975296,43.27436725282769&vs=Latest%20products;All%20products

### Which ARLAS component(s) are concerned by the bug?

Other

### If you chose 'Other', please specify the part(s) of ARLAS concerned by the bug.

Tour

### ARLAS version

23.1.0

### What browsers are you seeing the problem on?

Chrome

**Comment by MohamedHamouGisaia** [comment] 2024-07-04 09:28
we can't reproduce, closing

**Closed by MohamedHamouGisaia** 2024-07-04 09:28 UTC
Labels: type:bug
